### ISSUE TITLE
unhandled error size limiter

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#262]
I got this error in the log:
```
Jan 28 10:39:03 uk1 zone-mta: events.js:174
Jan 28 10:39:03 uk1 zone-mta:       throw er; // Unhandled 'error' event
Jan 28 10:39:03 uk1 zone-mta:       ^
Jan 28 10:39:03 uk1 zone-mta:
Jan 28 10:39:03 uk1 zone-mta: Error: Error: message exceeds fixed maximum message size 20971520 B (21292463 B)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter._flush (/usr/local/zonemta/node_modules/zone-mta/lib/size-limiter.js:40:23)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter.prefinish (_stream_transform.js:141:10)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter.emit (events.js:198:13)
Jan 28 10:39:03 uk1 zone-mta:     at prefinish (_stream_writable.js:635:14)
Jan 28 10:39:03 uk1 zone-mta:     at finishMaybe (_stream_writable.js:643:5)
Jan 28 10:39:03 uk1 zone-mta:     at endWritable (_stream_writable.js:663:3)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter.Writable.end (_stream_writable.js:594:5)
Jan 28 10:39:03 uk1 zone-mta:     at PassThrough.onend (_stream_readable.js:672:10)
Jan 28 10:39:03 uk1 zone-mta:     at Object.onceWrapper (events.js:286:20)
Jan 28 10:39:03 uk1 zone-mta:     at PassThrough.emit (events.js:198:13)
Jan 28 10:39:03 uk1 zone-mta: Emitted 'error' event at:
Jan 28 10:39:03 uk1 zone-mta:     at errorOrDestroy (internal/streams/destroy.js:107:12)
Jan 28 10:39:03 uk1 zone-mta:     at MessageSplitter.onerror (_stream_readable.js:734:7)
Jan 28 10:39:03 uk1 zone-mta:     at MessageSplitter.emit (events.js:198:13)
Jan 28 10:39:03 uk1 zone-mta:     at PassThrough.raw.once.err (/usr/local/zonemta/node_modules/zone-mta/lib/mail-drop.js:138:22)
Jan 28 10:39:03 uk1 zone-mta:     at Object.onceWrapper (events.js:286:20)
Jan 28 10:39:03 uk1 zone-mta:     at PassThrough.emit (events.js:203:15)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter.input.once.err (/usr/local/zonemta/node_modules/zone-mta/lib/plugin-handler.js:407:20)
Jan 28 10:39:03 uk1 zone-mta:     at Object.onceWrapper (events.js:286:20)
Jan 28 10:39:03 uk1 zone-mta:     at SizeLimiter.emit (events.js:203:15)
Jan 28 10:39:03 uk1 zone-mta:     at done (_stream_transform.js:208:19)
```

Eventually the process died all together.

**Comment by dazoot** [comment]
@andris9 noticed that only happens with big messages 20MB. If i reduce the limit can’t reproduce it. 

Any hint ?

**Comment by andris9** [comment]
Could you try v2.4.1? I fixed a bug handling large message errors. That size comes from this [config option](https://github.com/zone-eu/zone-mta/blob/bdf459b0f90e9a26a3632ef837e83a21cdfdbc50/config/default.js#L207).

**Comment by dazoot** [comment]
I get a startup error now:

```
Feb  1 20:00:55 dev zone-mta: > zone-mta-template@1.0.2 start /usr/local/zonemta
Feb  1 20:00:55 dev zone-mta: > node index.js --config=/etc/zonemta/zonemta.toml "--max-old-space-size=512"
Feb  1 20:00:55 dev zone-mta: 
Feb  1 20:00:56 dev zone-mta: /usr/local/zonemta/node_modules/js-yaml/index.js:10
Feb  1 20:00:56 dev zone-mta:     throw new Error('Function yaml.' + from + ' is removed in js-yaml 4. ' +
Feb  1 20:00:56 dev zone-mta:     ^
Feb  1 20:00:56 dev zone-mta: 
Feb  1 20:00:56 dev zone-mta: Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
Feb  1 20:00:56 dev zone-mta:     at Object.safeLoad (/usr/local/zonemta/node_modules/js-yaml/index.js:10:11)
Feb  1 20:00:56 dev zone-mta:     at Object.<anonymous> (/usr/local/zonemta/node_modules/zone-mta/lib/mail-queue.js:18:27)
Feb  1 20:00:56 dev zone-mta:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Feb  1 20:00:56 dev zone-mta:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Feb  1 20:00:56 dev zone-mta:     at Module.load (internal/modules/cjs/loader.js:653:32)
Feb  1 20:00:56 dev zone-mta:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Feb  1 20:00:56 dev zone-mta:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Feb  1 20:00:56 dev zone-mta:     at Module.require (internal/modules/cjs/loader.js:692:17)
Feb  1 20:00:56 dev zone-mta:     at require (internal/modules/cjs/helpers.js:25:18)
Feb  1 20:00:56 dev zone-mta:     at Object.<anonymous> (/usr/local/zonemta/node_modules/zone-mta/app.js:26:19)
```

**Comment by andris9** [comment]
Check your package.json that zone-mta is 2.4.1 and not 2.4.0

**Comment by dazoot** [comment]
yes that was it (2.4.1) yaml load fixed but my test still fails after 2.4.1 update.

```
Feb  1 20:12:27 dev zone-mta: info Child/dev/9709 [bd1bc08b145d02617a6d] Spawning sender process for dev
Feb  1 20:12:28 dev zone-mta: events.js:174
Feb  1 20:12:28 dev zone-mta:       throw er; // Unhandled 'error' event
Feb  1 20:12:28 dev zone-mta:       ^
Feb  1 20:12:28 dev zone-mta: 
Feb  1 20:12:28 dev zone-mta: SMTPResponse: Error: message exceeds fixed maximum message size 20971520 B (21276300 B)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter._flush (/usr/local/zonemta/node_modules/zone-mta/lib/size-limiter.js:40:23)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter.prefinish (_stream_transform.js:141:10)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter.emit (events.js:198:13)
Feb  1 20:12:28 dev zone-mta:     at prefinish (_stream_writable.js:635:14)
Feb  1 20:12:28 dev zone-mta:     at finishMaybe (_stream_writable.js:643:5)
Feb  1 20:12:28 dev zone-mta:     at endWritable (_stream_writable.js:663:3)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter.Writable.end (_stream_writable.js:594:5)
Feb  1 20:12:28 dev zone-mta:     at PassThrough.onend (_stream_readable.js:672:10)
Feb  1 20:12:28 dev zone-mta:     at Object.onceWrapper (events.js:286:20)
Feb  1 20:12:28 dev zone-mta:     at PassThrough.emit (events.js:198:13)
Feb  1 20:12:28 dev zone-mta: Emitted 'error' event at:
Feb  1 20:12:28 dev zone-mta:     at errorOrDestroy (internal/streams/destroy.js:107:12)
Feb  1 20:12:28 dev zone-mta:     at MessageSplitter.onerror (_stream_readable.js:734:7)
Feb  1 20:12:28 dev zone-mta:     at MessageSplitter.emit (events.js:198:13)
Feb  1 20:12:28 dev zone-mta:     at PassThrough.raw.once.err (/usr/local/zonemta/node_modules/zone-mta/lib/mail-drop.js:138:22)
Feb  1 20:12:28 dev zone-mta:     at Object.onceWrapper (events.js:286:20)
Feb  1 20:12:28 dev zone-mta:     at PassThrough.emit (events.js:203:15)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter.input.once.err (/usr/local/zonemta/node_modules/zone-mta/lib/plugin-handler.js:407:20)
Feb  1 20:12:28 dev zone-mta:     at Object.onceWrapper (events.js:286:20)
Feb  1 20:12:28 dev zone-mta:     at SizeLimiter.emit (events.js:203:15)
Feb  1 20:12:28 dev zone-mta:     at done (_stream_transform.js:208:19)
Feb  1 20:12:28 dev zone-mta: ERR! SMTP/feeder/9440 Reciver process f3bd4ce2dba211c87b8a for feeder exited with 1
```

**Comment by dazoot** [comment]
2.4.2 fixed it

```
Feb  2 09:40:49 dev zone-mta: info StoreStream 17761afce1a0000d25 SMTPFAIL Error: message exceeds fixed maximum message size 20971520 B (21276300 B)
```

Thanks.
